name: CI

on:
  push:
    tags:
      - 'v**'
    branches:
      - '**'
  pull_request:

  workflow_dispatch:

  # to execute once a day (more info see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule )
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ci-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-check:
    runs-on: ubuntu-latest
    container:
      image: 'ubuntu:26.04'
    steps:
      - name: Update system dependencies
        run: |
          apt update --yes

      - name: Install system dependencies
        run: |
          apt install --yes npm git

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run git+githubCI workaround
        run: |
          # We need this step so we can change the files using `npx prettier --write` in the format step, see https://github.com/actions/checkout/issues/363
          # Otherwise we get 'warning: Not a git repository. Use --no-index to compare two paths outside a working tree' in next step when trying to git diff
          git config --global --add safe.directory $PWD

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Format check
        run: |
          npm run format
          git diff --exit-code || (echo "Formatting did not match (see above diff), please run 'npm run format'" >&2 && exit 1)

